package com.lwx.mvprx.data.local;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.lwx.mvprx.data.local.Girls;
import com.lwx.mvprx.data.local.GirlsUrls;

import com.lwx.mvprx.data.local.GirlsDao;
import com.lwx.mvprx.data.local.GirlsUrlsDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig girlsDaoConfig;
    private final DaoConfig girlsUrlsDaoConfig;

    private final GirlsDao girlsDao;
    private final GirlsUrlsDao girlsUrlsDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        girlsDaoConfig = daoConfigMap.get(GirlsDao.class).clone();
        girlsDaoConfig.initIdentityScope(type);

        girlsUrlsDaoConfig = daoConfigMap.get(GirlsUrlsDao.class).clone();
        girlsUrlsDaoConfig.initIdentityScope(type);

        girlsDao = new GirlsDao(girlsDaoConfig, this);
        girlsUrlsDao = new GirlsUrlsDao(girlsUrlsDaoConfig, this);

        registerDao(Girls.class, girlsDao);
        registerDao(GirlsUrls.class, girlsUrlsDao);
    }
    
    public void clear() {
        girlsDaoConfig.clearIdentityScope();
        girlsUrlsDaoConfig.clearIdentityScope();
    }

    public GirlsDao getGirlsDao() {
        return girlsDao;
    }

    public GirlsUrlsDao getGirlsUrlsDao() {
        return girlsUrlsDao;
    }

}
